/*
Copyright (c) 2012 Tony Germaneri
Permission is hereby granted,
 free of charge, to any person obtaining a copy of this software 
and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, 
sublicense, and/or sell copies of the Software, and to permit 
persons to whom the Software is furnished to do so, subject to the
 following conditions:
The above copyright notice and this 
permission notice shall be included in all copies or substantial 
portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", 
WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR 
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR 
OTHERWISE, AR
SING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
// this file is used in a String.Format command in Main.HtmlExceptionMsg
// these are the arguments:
//
// fileName, message, lineNumber, sourceCode, source, stackTrace
// 
namespace Rendition {
    internal partial class Main:IHttpModule {
        #region Constants
        /// <summary>
	    /// The error message generated by the
	    /// http module.
	    /// </summary>
	    internal const string defaultErrorReport = @"<style>
body {{
	background: #555;
	color: white;
	font-family: Trebuchet MS,Arial,Sans-serif;
	margin:0;
}}
table th {{
	vertical-align: top;
	padding:5px;
    background:#333;
	text-shadow: 4px 4px 4px #000;
    border:solid 1px black;
	text-align:right;
}}
table td {{
	vertical-align: top;
	padding:5px;
    border:solid 1px black;
    background:#222;
}}
table td textarea {{
	font-size:10px;
	overflow:auto;
    width:95%;
	font-family: Trebuchet MS,Arial,Sans-serif;
    border:none;
    background:black;
    color:Gold;
	padding:10px;
	height:300px;
}}
table {{
	border-collapse: collapse;
    margin:auto;
	width:95%;
}}
h1 {{
	background:#333;
	padding:10px;
	text-shadow: 4px 4px 4px #000;
	margin:0;
    border-bottom:solid 4px #000;
}}
.source {{
    padding:0;
}}
.sourceCode {{
    margin:0;
    width:100%;
    border:none;
}}
.source td, .source th {{
    border:none;
    text-shadow:none;
    padding:0;
}}
.source td {{
    background:black;
    padding-left:5px;
}}
.source th {{
    background:black;
    color:gold;
}}
.errorLine td, .errorLine th {{
    background:darkred;
}}

		</style>
		<div>
			<table>
				<tr>
					<th>File Name</th>
					<td>{0}</td>
				</tr>
				<tr>
					<th>Message</th>
					<td>{1}</td>
				</tr>
				<tr>
					<th>Line</th>
					<td>{2}</td>
				</tr>
				<tr>
					<th>Source</th>
					<td>{4}</td>
				</tr>
				<tr>
					<td colspan=""2"" class=""source"">{3}</td>
				</tr>
				<tr>
					<th>Stack Trace</th>
					<td><textarea wrap=""off"" spellcheck=""false"">{5}</textarea></td>
				</tr>
			</table>
		</div>
		";
        #endregion
    }
}
